### ISSUE TITLE
Font isn't loading on production

### ISSUE THREAD

**Issue by reefdog** [OpenTechStrategies/arches-app-exp#100]
In production, the font is trying (and failing) to load from the path `https://arches-app-demo.opentechstrategies.com/assets/inter-latin-wght-normal-[signature].woff2`. But other static assets are coming from `https://arches-app-demo.opentechstrategies.com/static/archesdataviewer/vite_build/assets/*`.

I suspect there is some build-fu — or perhaps Fontsource-configuration — that we need to do to make sure the font is correctly referenced.

**Comment by reefdog** [comment]
The fonts are being correctly built to the target directory: https://github.com/OpenTechStrategies/arches-app-exp/tree/main/archesdataviewer/static/vite_build/assets

But Fontsource isn't aware of that location, I guess?

**Comment by hminsky2002** [comment]
@reefdog this has been plaguing me since we introduced the font. Because of nginx config [defined here](https://github.com/OpenTechStrategies/arches-app-exp/blob/main/archesdataviewer/README.md), we are serving everything from the `archesdataviewer/static` directory from `static/archesdataviewer`. For reference, navigating to https://arches-app-demo.opentechstrategies.com/static/archesdataviewer/vite_build/assets/inter-latin-wght-normal-C2S99t-D.woff2 will indeed download you the fonts. Is there any way to customize the font-source url that it seeks the font from?

**Comment by reefdog** [comment]
@hminsky2002 Oh, I missed your reply here somehow.

> Is there any way to customize the font-source url that it seeks the font from?

This is what I'm hoping to find! There's not any word of that in the [(sparse) documentation](https://fontsource.org/docs/getting-started/introduction), but I hold out hope for that. Before we commit to the CDN route — the site's not _broken_ without it, it just looks a bit plainer — I'm going to explore this a little more, ping the devs, etc.

**Comment by reefdog** [comment]
Okay, so: I'm going to solve this the _coward's way_, also known as the _way I probably should have explored in the beginning_: re-evaulating whether we even want a custom font at all! Behold…

<details>
<summary>Using the <b>Inter</b> font…</summary>
<img width="1476" alt="font-stack-1-inter" src="https://github.com/user-attachments/assets/d2268a01-1a37-41d4-b238-2ef143372be0">
</details>

<details>
<summary>Using the <b>system-default</b> font stack (used by GitHub, et al)…</summary>
<img width="1476" alt="font-stack-1-default" src="https://github.com/user-attachments/assets/ba5725f3-0006-4195-aa44-ef1df11038bc">
</details>

There are miniscule ways in which I prefer Inter, but not nearly enough to justify the trouble -- or even the additional network weight. I'm going to just remove the custom font entirely.
